### PR TITLE
fix: 修复issues:#81,#83,#84

### PR DESCRIPTION
**Pull request by yibingxiong**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| New feature?     | no
| BC breaks?       | no
| Deprecations?    |no
| New tests added? | not needed
| Fixed tickets    | #81,#83,#84
| License          | MIT

### Description

请参考以上提到的issues id

--

#### Please, don't submit `/dist` files with your PR!

> 首次pr， 请帮忙review一下代码哦！谢了:blush:

### CODE REVIEW

**Comment by yibingxiong** [comment]
这个项目没人维护了吗

**Comment by Jocs** [comment]
@yibingxiong 我周末 review 下，谢谢

**Comment by yibingxiong** [comment]
@Jocs 😄

**Comment by Jocs** [comment]
@yibingxiong 别着急，我需要测试下

**Pull request closed without merging**
