### PR TITLE
fix a typo in README

### PR DESCRIPTION
**Pull request by HangYang**
| Q                | A
| ---------------- | ---
| Bug fix?         | no
| New feature?     |no
| BC breaks?       |no
| Deprecations?    |no
| New tests added? | not needed
| Fixed tickets    | no
| License          | MIT

### Description

Just a typo fix in the readme file

--

### CODE REVIEW

**Comment by yibingxiong** [comment]
😁这也可以

**Comment by HangYang** [comment]
> 😁这也可以
@yibingxiong 看文档时候看到了顺手修一下嘛 😝

**Comment by yibingxiong** [comment]
💪 我第一次发pr， 也不知道大佬能不能给合

**Comment by Jocs** [comment]
谢谢你的 PR

**Pull request merged**
